name: Continuous deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      
      - name: Rust Cache
        uses: Swatinem/rust-cache@v1
      
      - name: Install Trunk
        uses: jetli/trunk-action@v0.1.0
      
      - name: Build with Trunk
        run: |
          trunk build --release
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          single-commit: true
